### ISSUE TITLE
INVALID FIRST CHUNK

### ISSUE THREAD

**Issue by zhouq123** [CaffeMrDe/BundleFusion_with_realsene2#1]

**Comment by CaffeMrDe** [comment]
你可以先抽取几帧图像后,再跑DirectX的循环代码

**Comment by chethanab16** [comment]
@CaffeMrDe By referring this Issue niessner/mLib#11 I found that you solved the following highLighted problem, Now I am facing the same Issue with VS 2017 and VS 2015 Could you please give me some suggestion how to solve this issue , thank you.

1>d:\3dre\bundlefusion\external\mlib\include\application-d3d11\d3d11canvas2d.h(302): error C2280: “ml::D3D11Canvas2D::ElementBillboard::ElementBillboard(const ml::D3D11Canvas2D::ElementBillboard &)”:
